### ISSUE TITLE
GameTest lagt wenns länger als 1min lauft

### ISSUE THREAD

**Issue by zpfisd-bbc** [zperee-bbc/MonkeyBanana#2]
Wenn GameClient.java länger als 1min lauft fangts langsam ah lagge und de spieler bewegt sich nüm flüssig. Ich glaube dass es irgend öppis wos eigentlich nüm brüchti nid automatisch löscht.

**Comment by zpfisd-bbc** [comment]
Het drah glege das ich vergesse han alli Obstacle objekt nur bim erste mal in obstArray iezschribe...
Han das eigentlich shomal gfixt gha, hans aber irgendwie wieder useglöscht gha.

**Comment by zperee** [comment]
Seisch bisch am schaffe :smile:

**Comment by zpfisd-bbc** [comment]
Easy pro halt :+1:

**Comment by zperee** [comment]
haha ja scho :+1:
